--- #YAML:1.0
name:                Acme-ProgressBar
version:             1.124
abstract:            a simple progress bar for the patient
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    Exporter:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo SIGNES <rjbs@cpan.org>
