--- #YAML:1.0
name:               Acme-ProgressBar
version:            1.125
abstract:           a simple progress bar for the patient
author:
    - Ricardo SIGNES <rjbs@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Exporter:  0
resources:
    Repository:  http://github.com/rjbs/acme-progressbar
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
